  autocomplete_search_jquery[m
  autocomplete_search_jquery_tmp[m
  causes_events_blogs_associations[m
  cronjob_whenever_delayedjob[m
  d[m
  delegate_and_export_csv[m
  friendly_id[m
  fundus_review[m
  hop_hompage[m
  integrate_ckeditor[m
  integrated_googlemap_API[m
  master[m
* [32mparanoid_safe_destroy[m
  payment_with_paypal[m
  rails_admin_authorize[m
  search_with_ransack[m
  share_comment_plugin_social[m
  user_devise[m
  user_devise_FB[m
  user_devise_mailer[m
